REDIS_PATH := Redis

start-redis:
	@./$(REDIS_PATH)/redis-server.exe ./$(REDIS_PATH)/redis.conf &

load-redis-data: # Курсы валют к доллару США согласно ЦБ РФ на 04.03.2022
	@./$(REDIS_PATH)/redis-cli.exe set USD 1.0
	@./$(REDIS_PATH)/redis-cli.exe set RUR 83.4285
	@./$(REDIS_PATH)/redis-cli.exe set ALL 111.65
	@./$(REDIS_PATH)/redis-cli.exe set DZD 142.2332
	@./$(REDIS_PATH)/redis-cli.exe set AOA 496.1
	@./$(REDIS_PATH)/redis-cli.exe set ARS 108.04
	@./$(REDIS_PATH)/redis-cli.exe set AWG 1.81
	@./$(REDIS_PATH)/redis-cli.exe set AFN 89.78
	@./$(REDIS_PATH)/redis-cli.exe set BSD 1.0
	@./$(REDIS_PATH)/redis-cli.exe set BDT 86.145
	@./$(REDIS_PATH)/redis-cli.exe set BBD 2.0191
	@./$(REDIS_PATH)/redis-cli.exe set BHD 0.377
	@./$(REDIS_PATH)/redis-cli.exe set BZD 2.0157
	@./$(REDIS_PATH)/redis-cli.exe set BMD 1.0
	@./$(REDIS_PATH)/redis-cli.exe set BOB 6.875
	@./$(REDIS_PATH)/redis-cli.exe set BWP 11.78994
	@./$(REDIS_PATH)/redis-cli.exe set BND 1.3594
	@./$(REDIS_PATH)/redis-cli.exe set BIF 1999.5
	@./$(REDIS_PATH)/redis-cli.exe set BTN 76.0005
	@./$(REDIS_PATH)/redis-cli.exe set VUV 112.625
	@./$(REDIS_PATH)/redis-cli.exe set VES 4.3629
	@./$(REDIS_PATH)/redis-cli.exe set XCD 2.71
	@./$(REDIS_PATH)/redis-cli.exe set VND 22840.0
	@./$(REDIS_PATH)/redis-cli.exe set HTG 105.5
	@./$(REDIS_PATH)/redis-cli.exe set GYD 209.215
	@./$(REDIS_PATH)/redis-cli.exe set GMD 53.375
	@./$(REDIS_PATH)/redis-cli.exe set GHS 6.975
	@./$(REDIS_PATH)/redis-cli.exe set GTQ 7.71
	@./$(REDIS_PATH)/redis-cli.exe set GNF 8973.5
	@./$(REDIS_PATH)/redis-cli.exe set GIP 0.75
	@./$(REDIS_PATH)/redis-cli.exe set HNL 24.6234
	@./$(REDIS_PATH)/redis-cli.exe set GEL 3.25
	@./$(REDIS_PATH)/redis-cli.exe set MKD 55.94
	@./$(REDIS_PATH)/redis-cli.exe set AED 3.673
	@./$(REDIS_PATH)/redis-cli.exe set STN 22.4693
	@./$(REDIS_PATH)/redis-cli.exe set NAD 15.2404
	@./$(REDIS_PATH)/redis-cli.exe set SBD 8.07
	@./$(REDIS_PATH)/redis-cli.exe set TTD 6.7862
	@./$(REDIS_PATH)/redis-cli.exe set FJD 2.11
	@./$(REDIS_PATH)/redis-cli.exe set DOP 54.83
	@./$(REDIS_PATH)/redis-cli.exe set EGP 15.735
	@./$(REDIS_PATH)/redis-cli.exe set ZMW 18.01
	@./$(REDIS_PATH)/redis-cli.exe set IDR 14391.1875
	@./$(REDIS_PATH)/redis-cli.exe set JOD 0.709
	@./$(REDIS_PATH)/redis-cli.exe set IQD 1459.52
	@./$(REDIS_PATH)/redis-cli.exe set IRR 42000.0
	@./$(REDIS_PATH)/redis-cli.exe set ISK 130.2
	@./$(REDIS_PATH)/redis-cli.exe set YER 250.25
	@./$(REDIS_PATH)/redis-cli.exe set KHR 4065.0
	@./$(REDIS_PATH)/redis-cli.exe set QAR 3.6497
	@./$(REDIS_PATH)/redis-cli.exe set KES 113.925
	@./$(REDIS_PATH)/redis-cli.exe set PGK 3.52
	@./$(REDIS_PATH)/redis-cli.exe set COP 3759.445
	@./$(REDIS_PATH)/redis-cli.exe set KMF 445.51
	@./$(REDIS_PATH)/redis-cli.exe set BAM 1.78
	@./$(REDIS_PATH)/redis-cli.exe set CDF 2001.14
	@./$(REDIS_PATH)/redis-cli.exe set CRC 643.435
	@./$(REDIS_PATH)/redis-cli.exe set CUP 24.0
	@./$(REDIS_PATH)/redis-cli.exe set KWD 0.3034
	@./$(REDIS_PATH)/redis-cli.exe set LAK 11464.0
	@./$(REDIS_PATH)/redis-cli.exe set LRD 154.3
	@./$(REDIS_PATH)/redis-cli.exe set LBP 1512.2
	@./$(REDIS_PATH)/redis-cli.exe set LYD 4.6238
	@./$(REDIS_PATH)/redis-cli.exe set MUR 43.85
	@./$(REDIS_PATH)/redis-cli.exe set MRU 36.3901
	@./$(REDIS_PATH)/redis-cli.exe set MWK 803.65
	@./$(REDIS_PATH)/redis-cli.exe set MGA 3995.50
	@./$(REDIS_PATH)/redis-cli.exe set MYR 4.177
	@./$(REDIS_PATH)/redis-cli.exe set MVR 15.46
	@./$(REDIS_PATH)/redis-cli.exe set MAD 9.6583
	@./$(REDIS_PATH)/redis-cli.exe set MXN 20.6828
	@./$(REDIS_PATH)/redis-cli.exe set MZN 64.1
	@./$(REDIS_PATH)/redis-cli.exe set MNT 2880.0
	@./$(REDIS_PATH)/redis-cli.exe set NPR 121.805
	@./$(REDIS_PATH)/redis-cli.exe set NGN 415.96
	@./$(REDIS_PATH)/redis-cli.exe set NIO 35.755
	@./$(REDIS_PATH)/redis-cli.exe set NZD 1.464
	@./$(REDIS_PATH)/redis-cli.exe set ILS 3.2547
	@./$(REDIS_PATH)/redis-cli.exe set TWD 28.1255
	@./$(REDIS_PATH)/redis-cli.exe set OMR 0.385
	@./$(REDIS_PATH)/redis-cli.exe set TOP 2.265
	@./$(REDIS_PATH)/redis-cli.exe set PKR 178.225
	@./$(REDIS_PATH)/redis-cli.exe set PYG 6986.96
	@./$(REDIS_PATH)/redis-cli.exe set MOP 8.0555
	@./$(REDIS_PATH)/redis-cli.exe set PEN 3.7305
	@./$(REDIS_PATH)/redis-cli.exe set SVC 8.7545
	@./$(REDIS_PATH)/redis-cli.exe set SAR 3.7519
	@./$(REDIS_PATH)/redis-cli.exe set SZL 15.2382
	@./$(REDIS_PATH)/redis-cli.exe set KPW 130.0
	@./$(REDIS_PATH)/redis-cli.exe set SCR 14.4
	@./$(REDIS_PATH)/redis-cli.exe set RSD 106.81
	@./$(REDIS_PATH)/redis-cli.exe set SYP 2512.5
	@./$(REDIS_PATH)/redis-cli.exe set SOS 578.5
	@./$(REDIS_PATH)/redis-cli.exe set SDG 446.2242
	@./$(REDIS_PATH)/redis-cli.exe set SRD 20.503
	@./$(REDIS_PATH)/redis-cli.exe set SLL 11640.0
	@./$(REDIS_PATH)/redis-cli.exe set THB 32.615
	@./$(REDIS_PATH)/redis-cli.exe set TZS 2315.0
	@./$(REDIS_PATH)/redis-cli.exe set TND 2.931
	@./$(REDIS_PATH)/redis-cli.exe set UGX 3562.5
	@./$(REDIS_PATH)/redis-cli.exe set UYU 42.735
	@./$(REDIS_PATH)/redis-cli.exe set PHP 51.81
	@./$(REDIS_PATH)/redis-cli.exe set DJF 178.025
	@./$(REDIS_PATH)/redis-cli.exe set XAF 602.625
	@./$(REDIS_PATH)/redis-cli.exe set XOF 596.5
	@./$(REDIS_PATH)/redis-cli.exe set RWF 1017.0
	@./$(REDIS_PATH)/redis-cli.exe set SHP 0.7471
	@./$(REDIS_PATH)/redis-cli.exe set FKP 0.75
	@./$(REDIS_PATH)/redis-cli.exe set HRK 6.8656
	@./$(REDIS_PATH)/redis-cli.exe set CLP 796.125
	@./$(REDIS_PATH)/redis-cli.exe set LKR 202.0
	@./$(REDIS_PATH)/redis-cli.exe set ERN 15.075
	@./$(REDIS_PATH)/redis-cli.exe set CVE 100.57
	@./$(REDIS_PATH)/redis-cli.exe set ETB 51.2762
	@./$(REDIS_PATH)/redis-cli.exe set JMD 154.375
	@./$(REDIS_PATH)/redis-cli.exe set EUR 0.90553

run-app: start-redis load-redis-data
	@python3 app/main.py

.PHONY: start-redis load-redis-data run-app stop-redis
